# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-23 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0037_auto_20200116_1201'),
        ('press', '0021_auto_20190329_1202'),
        ('cms', '0002_migrate_issue_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMSBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columns', models.PositiveIntegerField(blank=True, choices=[(4, '1/4'), (6, '1/2'), (8, '2/3'), (12, '1')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CMSPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Page name displayed at the top of the page', max_length=300)),
                ('builtin', models.BooleanField(default=False)),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.Journal')),
                ('press', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='press.Press')),
            ],
        ),
        migrations.CreateModel(
            name='HTMLBlock',
            fields=[
                ('cmsblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms.CMSBlock')),
                ('content', models.TextField(blank=True, null=True)),
            ],
            bases=('cms.cmsblock',),
        ),
        migrations.AddField(
            model_name='cmsblock',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='cms.CMSPage'),
        ),
        migrations.CreateModel(
            name='CustomPage',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
            },
            bases=('cms.cmspage',),
        ),
        migrations.AlterUniqueTogether(
            name='cmspage',
            unique_together=set([('journal', 'press', 'title')]),
        ),
    ]
