# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-23 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20200123_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBlock',
            fields=[
                ('cmsblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms.CMSBlock')),
                ('title', models.CharField(help_text='Title to be displayed above the journal description', max_length=300)),
            ],
            bases=('cms.cmsblock',),
        ),
    ]
