# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-24 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_aboutblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsBlock',
            fields=[
                ('cmsblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms.CMSBlock')),
                ('total_articles', models.PositiveIntegerField(default=1, help_text='Maximum number of news articles to render')),
            ],
            bases=('cms.cmsblock',),
        ),
    ]
