# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-24 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0037_auto_20200116_1201'),
        ('cms', '0005_newsblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedJournalsBlock',
            fields=[
                ('cmsblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms.CMSBlock')),
                ('use_random_journals', models.BooleanField(default=False)),
                ('featured_journals', models.ManyToManyField(blank=True, null=True, to='journal.Journal')),
            ],
            bases=('cms.cmsblock',),
        ),
    ]
