# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-27 10:31
from __future__ import unicode_literals

import cms.models.blocks
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('submission', '0040_article_projected_issue'),
        ('cms', '0006_featuredjournalsblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMSFeaturedArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(blank=True, null=True)),
                ('added', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(blank=True, default=cms.models.blocks.get_user_from_request, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission.Article')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='FeaturedArticlesBlock',
            fields=[
                ('cmsblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cms.CMSBlock')),
                ('featured_articles', models.ManyToManyField(blank=True, null=True, through='cms.CMSFeaturedArticle', to='submission.Article')),
            ],
            bases=('cms.cmsblock',),
        ),
        migrations.AddField(
            model_name='cmsfeaturedarticle',
            name='cms_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.FeaturedArticlesBlock'),
        ),
    ]
