# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-28 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0040_article_projected_issue'),
        ('cms', '0007_auto_20200127_1031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cmsfeaturedarticle',
            options={},
        ),
        migrations.AddField(
            model_name='cmsblock',
            name='sequence',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='cmsfeaturedarticle',
            unique_together=set([('article', 'cms_block')]),
        ),
    ]
