# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-28 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_cms_block_sequence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutblock',
            options={'verbose_name': 'About Block', 'verbose_name_plural': 'About Blocks'},
        ),
        migrations.AlterModelOptions(
            name='cmsfeaturedarticle',
            options={'verbose_name': 'Featured Journals Block', 'verbose_name_plural': 'Featured Journals Blocks'},
        ),
        migrations.AlterModelOptions(
            name='featuredjournalsblock',
            options={'verbose_name': 'Featured Journals Block', 'verbose_name_plural': 'Featured Journals Blocks'},
        ),
        migrations.AlterModelOptions(
            name='htmlblock',
            options={'verbose_name': 'HTML Block', 'verbose_name_plural': 'HTML Blocks'},
        ),
        migrations.AlterModelOptions(
            name='newsblock',
            options={'verbose_name': 'News Block', 'verbose_name_plural': 'News Blocks'},
        ),
    ]
